spring:
  #导入数据源
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672

  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougou11-28?characterEncoding=utf-8&serverTimezone=UTC
      #solr
      #application:
      #name: solr
      #data:
      # solr:
      # host: http://127.0.0.1:8080/solr

      #  redis:
      # database: 0
      # host: 127.0.0.1
      #port: 6379
      #  password:
      #timeout: 3000ms
      #jedis:
      #  pool:
      # max-idle: 500
      # min-idle: 50
    # max-active: 2000
    #  max-wait: 1000ms
    #静态资源添加
mvc:
  static-path-pattern: /static/**
  #mybatis的映射
mybatis:
  # 指定Mapper映射的模型类
  type-aliases-package: com.example.bean
  # 指定sql映射文件位置
  mapper-locations: classpath:static/mybatis/*.xml
server:
  port: 9105









